source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hyperledger/indy-sdk.git'
platform :ios, '12.2'
inhibit_all_warnings!

target 'swiftIosApp' do
    use_frameworks!
    pod 'libsodium', '~> 1.0.12'
    pod 'libzmq-pw', "4.2.2"
    pod 'PocketSocket', '1.0.1'
    pod 'ssi_agent', "0.0.6", :source => "https://github.com/Lumedic/ssi-mobile-sdk.git"
    #Comment out line above and uncomment 3 lines below for local build
    #pod 'kotlin_multiplatform_agent', :path => '../../'
    #pod 'OpenSSL-XM',  '~> 1.0.210.1'
    #pod 'libindy', "1.15.0"

    # Pods for swiftIosApp

    target 'swiftIosAppTests' do
      inherit! :search_paths
      # Pods for testing
    end

    target 'swiftIosAppUITests' do
      # Pods for testing
    end
end


#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      if target.name == 'libzmq-pw'
#        target.build_configurations.each do |config|
#            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ZMQ_BUILD_DRAFT_API=1']
#        end
#      end
#      if target.name == 'libsodium'
#        target.build_configurations.each do |config|
#            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'NATIVE_LITTLE_ENDIAN=1 PACKAGE_NAME=\"libsodium\" PACKAGE_TARNAME=\"libsodium\" PACKAGE_VERSION=\"1.0.12\" PACKAGE_STRING=\"libsodium\ 1.0.12\" PACKAGE_BUGREPORT=\"https://github.com/jedisct1/libsodium/issues\" PACKAGE_URL=\"https://github.com/jedisct1/libsodium\" PACKAGE=\"libsodium\" VERSION=\"1.0.12\" HAVE_PTHREAD_PRIO_INHERIT=1 HAVE_PTHREAD=1 STDC_HEADERS=1 HAVE_SYS_TYPES_H=1 HAVE_SYS_STAT_H=1 HAVE_STDLIB_H=1 HAVE_STRING_H=1 HAVE_MEMORY_H=1 HAVE_STRINGS_H=1 HAVE_INTTYPES_H=1 HAVE_STDINT_H=1 HAVE_UNISTD_H=1 _POSIX_PTHREAD_SEMANTICS=1 NATIVE_LITTLE_ENDIAN=1 HAVE_WEAK_SYMBOLS=1 CPU_UNALIGNED_ACCESS=1 CONFIGURED=1']
#        end
#      end
#    end
#end
